### ISSUE TITLE
CMake does not build an x64 version of the lib

### ISSUE THREAD

**Issue by morphogencc** [sirikata/liboauthcpp#17]
I'd like to build an x64 compatible version for my project (which is x64), but the solution provided by CMake doesn't provide the option.  Is there a way to add this functionality to CMake?  I'm not very familiar with the tool, unfortunately :(

**Comment by ewencp** [comment]
@morphogencc You can do this via compiler flags. See this [stackoverflow answer](http://stackoverflow.com/a/5359572/841827) for how to do this on various platforms. There's a CMake CLI "GUI" that you can use that can make it easy to configure these -- run `ccmake .` from the `build/` directory.

**Comment by morphogencc** [comment]
Great; I was able to reset the generator and then set it up for a x64 build.  Thanks!
