### ISSUE TITLE
Beautiful library!

### ISSUE THREAD

**Issue by vinniefalco** [sirikata/liboauthcpp#19]
I just stumbled across this library, and I very much agree with this idea that the interface does not provide network services, just pure OAuth functionality - you "BYONI" (Bring Your Own Networking Interface). What do you think about leveraging Beast's HTTP message model to generate complete messages which Beast can send?
https://github.com/vinniefalco/Beast

Thanks!

**Comment by ewencp** [comment]
@vinniefalco Not sure what you'd be looking for here since the intent is to remain agnostic to the networking layer. Since Beast seems to provide builder-style interfaces for requests, the integration seems like it would be pretty minimal anyway, right?

**Comment by ewencp** [comment]
No follow up, so going to close. Feel free to re-open if there's some concrete next steps you'd like to propose.
